sonar.projectKey=Survivor
sonar.projectName=Survivor
sonar.sources=backend,frontend
sonar.exclusions=**/node_modules/**,**/*_test.go,**/dist/**,**/vendor/**

sonar.go.coverage.reportPaths=backend/coverage.out
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info