services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: motdepasse123
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../GeoEmploiDB.sql:/docker-entrypoint-initdb.d/GeoEmploiDB.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - project_network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8080
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: motdepasse123
      DB_NAME: mydb
      DB_SSLMODE: disable
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - project_network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - project_network

volumes:
  postgres_data:

networks:
  project_network:
    driver: bridge
